# Generated by Django 2.2.6 on 2020-04-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_books_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
