# Generated by Django 2.2.6 on 2019-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=100)),
                ('path_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_path',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='some-string'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=100)),
                ('tutorial_content', models.TextField()),
                ('courses', models.ManyToManyField(blank=True, related_name='tutorials', to='learn.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='paths',
            field=models.ManyToManyField(blank=True, to='learn.Path'),
        ),
    ]
