# Generated by Django 2.2.6 on 2019-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20191103_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='slug',
            field=models.SlugField(default='some-string'),
        ),
    ]
