# Generated by Django 2.2.6 on 2019-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_path_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
