# Generated by Django 2.2.6 on 2019-11-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(default='some-string'),
        ),
    ]
