# Generated by Django 2.2.6 on 2019-12-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20191201_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('guide_details', models.TextField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Course')),
            ],
        ),
    ]
