# Generated by Django 2.2.6 on 2019-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='guide_snippet',
            field=models.CharField(default='some-string', max_length=100),
        ),
    ]
