# Generated by Django 2.2.6 on 2020-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200406_0955'),
        ('learn', '0012_course_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_details', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='some-string')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='paths',
        ),
        migrations.DeleteModel(
            name='Path',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, to='learn.Category'),
        ),
    ]
