# Generated by Django 2.2.6 on 2020-04-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_auto_20200406_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Essay',
        ),
        migrations.RenameField(
            model_name='essay',
            old_name='course_content',
            new_name='essay_content',
        ),
        migrations.RenameField(
            model_name='essay',
            old_name='course_details',
            new_name='essay_details',
        ),
        migrations.RenameField(
            model_name='essay',
            old_name='course_title',
            new_name='essay_title',
        ),
    ]
